language: node_js
node_js:
- '8'

cache:
  directories:
  - node_modules
  - bundle/cache

before_install:
- openssl aes-256-cbc -K $encrypted_194431d92fdc_key -iv $encrypted_194431d92fdc_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod +x ./.build_scripts/build.sh
- chmod +x ./.build_scripts/deploy.sh

script:
- "./.build_scripts/build.sh"

after_success:
- "./.build_scripts/deploy.sh"
