#!/usr/bin/env python3
import os
from csv_json_converters.overview_json_converter import convert_overview_type_csv_to_json
from csv_json_converters.multiple_services_json_converter import convert_multiple_services_type_csv_to_json
from csv_json_converters.indicator_overview_json_converter import convert_scores_overview_type_csv_to_indicator_overview_json
from csv_json_converters.all_indicator_json_converter import convert_scores_overview_type_csv_to_all_indicator_json
from csv_json_converters.index_service_json_converter import convert_multiple_services_type_csv_to_index_service_json
from csv_json_converters.categories_overview_json_converter import convert_scores_overview_type_csv_to_categories_overview_json
from csv_json_converters.difference_json_converter import convert_difference_type_to_json
from csv_json_converters.sub_indicators_json_converter import convert_sub_indicator_type_to_jsons

if __name__ == '__main__':
    current_dir = os.path.dirname(os.path.realpath(__file__))
    data_dir = os.path.join(current_dir, 'RDRIndex/2018data')
    quick_overview_csv_location = os.path.join(data_dir, 'Quick Overview.csv')
    services_list_csv_location = os.path.join(data_dir, 'Service Level Analysis.csv')
    scores_overview_csv_location = os.path.join(data_dir, 'Scores Overview.csv')
    difference_csv_location = os.path.join(data_dir, 'Difference.csv')
    governance_csv_location = os.path.join(data_dir, 'Governance Sub Indicators.csv')
    foe_csv_location = os.path.join(data_dir, 'Freedom of Expression Sub Indicators.csv')
    privacy_csv_location = os.path.join(data_dir, 'Privacy Sub Indicators.csv')
    output_directory = os.path.join(current_dir, 'output/')

    convert_overview_type_csv_to_json(quick_overview_csv_location, output_directory)
    convert_multiple_services_type_csv_to_json(services_list_csv_location, output_directory)
    convert_scores_overview_type_csv_to_indicator_overview_json(scores_overview_csv_location, output_directory)
    convert_scores_overview_type_csv_to_all_indicator_json(scores_overview_csv_location, output_directory,
                                                           check_csv_structure=False)
    # already checked in function convert_scores_overview_type_csv_to_indicator_overview_json
    convert_multiple_services_type_csv_to_index_service_json(services_list_csv_location, output_directory,
                                                             check_csv_structure=True)
    # it has additional checks for multiple services csv
    convert_scores_overview_type_csv_to_categories_overview_json(
        scores_overview_csv_location, quick_overview_csv_location, output_directory, check_csv_structure=True)
    convert_difference_type_to_json(difference_csv_location, output_directory)
    convert_sub_indicator_type_to_jsons(governance_csv_location, output_directory)
    convert_sub_indicator_type_to_jsons(foe_csv_location, output_directory)
    convert_sub_indicator_type_to_jsons(privacy_csv_location, output_directory)
    # for sub_indicator_csv_location in [governance_csv_location, foe_csv_location, privacy_csv_location]:
    #     convert_sub_indicator_type_to_jsons(sub_indicator_csv_location, output_directory)
